### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by wjstdu** [seismology-RUB/NEXD-3D#1]
When I run 'run_cubit.py', python has some errors as follows. My python version is 3.6.5 and installed successfully. I also put ' ....\Trelis 16.1\bin' into the sys.path of python.  I am a python beginner. Could you please help me find what the problem is？ Thank you very much.

Traceback (most recent call last):
  File "E:\Program Files\Python27\run_cubit.py", line 4, in <module>
    import cubit
  File "D:\Program Files\Trelis 16.1\bin\cubit.py", line 28, in <module>
    _cubit = swig_import_helper()
  File "D:\Program Files\Trelis 16.1\bin\cubit.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cubit', fp, pathname, description)
ImportError: DLL load failed

**Comment by mboxberg** [comment]
This is an issue related to Trelis/Cubit. The python script "cubit.py" cannot load the module '_cubit.dll' (or for a linux installation '_cubit.so'), which is – in my installation – contained in the same folder as the python script, which is in your case "D:\Program Files\Trelis 16.1\bin\". Please check your Trelis installation for the file "_cubit.dll". Maybe Trelis was not installed properly!?
